# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: "helm-s3-publisher"
    binary: "helm-s3-publisher"
    env:
      - CGO_ENABLED=0
      - USERNAME=carlosrfjunior
    main: ./cmd/helm-s3-publisher
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy={{ .Env.USERNAME }}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: plugin.yaml
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

# https://github.com/crazy-max/ghaction-import-gpg
signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

# https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
brews:
  - name: helm-s3-publisher
    repository:
      owner: toolsascode
      name: homebrew-tap
      token: "{{ .Env.PA_TOKEN }}"
    commit_author:
      name: carlosrfjunior
      email: carlosrfjunior@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    goarm: "7"
    homepage: "https://github.com/toolsascode/helm-s3-publisher"
    description: "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
    license: "Apache License 2.0"
    test: |
      system "#{bin}/helm-s3-publisher version"
    dependencies:
      - name: go
        type: optional
      - name: git
    extra_install: |-
      bash_completion.install "completions/helm-s3-publisher.bash" => "helm-s3-publisher"
      zsh_completion.install "completions/helm-s3-publisher.zsh" => "_helm-s3-publisher"
      fish_completion.install "completions/helm-s3-publisher.fish"
      man1.install "manpages/helm-s3-publisher.1.gz"

scoops:
  - repository:
      owner: toolsascode
      name: scoop-bucket
      token: "{{ .Env.PA_TOKEN }}"
    commit_author:
      name: carlosrfjunior
      email: carlosrfjunior@gmail.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    directory: bucket
    homepage: "https://github.com/toolsascode/helm-s3-publisher"
    description: "Go Modeler is a small CLI and Library that brings the powerful features of the golang template into a simplified form."
    license: "Apache License 2.0"