name: Testing
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get ./cmd/helm-s3-publisher
      - name: Build
        run: go build -o helm-s3-publisher -v ./cmd/helm-s3-publisher
      - name: Test with the Go CLI
        id: gotest
        run: |
          go test -coverprofile=coverage.out -cover ./... > report.out
          echo "coverage=$( cat report.out | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: Testing the CLI in basic mode
        run: make run
  